apiVersion: v1
kind: ConfigMap
metadata:
  name: "web-scraperd-sync-configmap"
data:
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  WORKER_QUEUE_NAME: {{ .Values.worker.queue }}
  WORKER_PORT: {{ .Values.worker.port | quote }}
  WORKER_HOST: {{ .Values.worker.host }}
  WORKER_SCHEDULE_ENDPOINT: {{ .Values.worker.endpoints.schedule }}
  WORKER_STATUS_ENDPOINT: {{ .Values.worker.endpoints.status }}
  WORKER_ADDVERSION_ENDPOINT: {{ .Values.worker.endpoints.addVersion }}
  MAX_PROCESS_PER_WORKER: {{ .Values.worker.maxNumProcesses | quote }}
  GIT_PROJ_ENDPOINT: {{ .Values.sync.gitEndpoint }}
