apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  labels:
    app.kubernetes.io/name: {{ include "web-scraperd.name" . }}
type: Opaque
data:
  redis-username: {{ .Values.username | b64enc | quote }}
  redis-password: {{ .Values.password | b64enc | quote }}